### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by rgarnau** [ForgeFlow/ddmrp#33]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

# Dependencies
OCA/web#435

 - [x] web_tree_many2one_clickable
 - [x] web_widget_x2many_2d_matrix
 - [x] web_widget_bokeh_chart
 - [x] web_tree_dynamic_colored_field

OCA/manufacture#157

 - [x] mrp_mto_with_stock
 - [x] mrp_bom_location - https://github.com/OCA/manufacture/pull/256

OCA/manufacture-reporting#14

 - [x] report_mrp_bom_matrix - https://github.com/OCA/manufacture-reporting/pull/38
 - [x] mrp_bom_current_stock - https://github.com/OCA/manufacture-reporting/pull/39

OCA/server-tools#565

 - [x] base_cron_exclusion

OCA/stock-logistics-warehouse#201

 - [x] stock_putaway_product
 - [x] stock_orderpoint_manual_procurement_uom
 - [x] stock_warehouse_orderpoint_stock_info
 - [x] stock_warehouse_orderpoint_stock_info_unreserved
 - [x] stock_demand_estimate
 - [x] stock_available_unreserved

## Modules to migrate
 - [x] ddmrp
 - [x] ddmrp_history
 - [x] ddmrp_adjustment
 - [x] ddmrp_product_replace - https://github.com/Eficent/ddmrp/pull/24

**Comment by hparfr** [comment]
report_mrp_bom_matrix and mrp_bom_current_stock are now merged.

**Comment by JordiBForgeFlow** [comment]
@hparfr updated. I also added dependency with mrp_multi_level

**Comment by LoisRForgeFlow** [comment]
I think we can close this, branch 10 is working since the barcelona workshop.
